import type { TelegramFs } from "./fs";
import type { TelegramPaths } from "./paths";

/**
 * Who authored a message in a chat transcript.
 * - `interlocutor`: the external person writing into the account.
 * - `owner`: the account holder (the human the bot writes on behalf of).
 * - `bot`: generated by the model/bot.
 */
export type ChatAuthor = "interlocutor" | "owner" | "bot";

export interface ChatMessageRecord {
	author: ChatAuthor;
	text: string;
	timestamp: number;
	senderId?: string;
	senderName?: string;
	messageId?: number;
	/** Attachment kind, if the message carried media. */
	kind?: string;
}

/**
 * Append-only per-chat transcript, one JSONL file per chat. This is the ACID
 * source of truth for the manager's last-N memory and for context isolation
 * (`pi.on("context")` rebuilds the model's messages from here). Reads tolerate
 * malformed trailing lines (e.g. a crash mid-append).
 */
export interface ChatStore {
	append(chatId: string, record: ChatMessageRecord): Promise<void>;
	/** Newest `limit` records, oldest-first. */
	getRecent(chatId: string, limit: number): Promise<ChatMessageRecord[]>;
	all(chatId: string): Promise<ChatMessageRecord[]>;
	/** True once a chat has at least one recorded message (first-contact check). */
	hasHistory(chatId: string): Promise<boolean>;
}

export function createChatStore(
	fs: TelegramFs,
	paths: TelegramPaths,
): ChatStore {
	async function readAll(chatId: string): Promise<ChatMessageRecord[]> {
		const path = paths.chatFile(chatId);
		if (!(await fs.exists(path))) {
			return [];
		}
		const text = await fs.readText(path);
		const records: ChatMessageRecord[] = [];
		for (const line of text.split("\n")) {
			if (!line.trim()) continue;
			try {
				records.push(JSON.parse(line) as ChatMessageRecord);
			} catch {
				// Tolerate a partial/corrupt trailing line from an interrupted append.
			}
		}
		return records;
	}

	return {
		async append(chatId, record) {
			await fs.appendText(
				paths.chatFile(chatId),
				`${JSON.stringify(record)}\n`,
			);
		},
		async getRecent(chatId, limit) {
			const all = await readAll(chatId);
			return limit >= 0 ? all.slice(-limit) : all;
		},
		all: readAll,
		async hasHistory(chatId) {
			const path = paths.chatFile(chatId);
			if (!(await fs.exists(path))) return false;
			return (await fs.readText(path)).trim().length > 0;
		},
	};
}
