import { withFileWriteLock } from "./file-lock";
import { safeReaddir, type TelegramFs } from "./fs";
import type { TelegramPaths } from "./paths";

/**
 * Who authored a message in a chat transcript.
 * - `interlocutor`: the external person writing into the account.
 * - `owner`: the account holder (the human the bot writes on behalf of).
 * - `bot`: generated by the model/bot.
 */
export type ChatAuthor = "interlocutor" | "owner" | "bot";

export interface ChatMessageRecord {
	author: ChatAuthor;
	text: string;
	timestamp: number;
	senderId?: string;
	senderName?: string;
	messageId?: number;
	/** Attachment kind, if the message carried media. */
	kind?: string;
}

/**
 * Append-only per-chat transcript, one JSONL file per chat. This is the ACID
 * source of truth for the manager's last-N memory and for context isolation
 * (`pi.on("context")` rebuilds the model's messages from here). Reads tolerate
 * malformed trailing lines (e.g. a crash mid-append).
 */
export interface ChatStore {
	append(chatId: string, record: ChatMessageRecord): Promise<void>;
	/** Newest `limit` records, oldest-first. */
	getRecent(chatId: string, limit: number): Promise<ChatMessageRecord[]>;
	all(chatId: string): Promise<ChatMessageRecord[]>;
	/** True once a chat has at least one recorded message (first-contact check). */
	hasHistory(chatId: string): Promise<boolean>;
	/** Every chat id with a stored transcript (for catch-up scanning). */
	listChatIds(): Promise<string[]>;
}

/**
 * @param retentionLimit When > 0, the transcript on disk is compacted to the
 * last `retentionLimit` messages once it grows past twice that — so old messages
 * are pruned and the file stays bounded (to ~2× the limit) instead of growing
 * forever. Omit/0 to keep the full append-only log. Callers pass the manager's
 * `rememberMessages` (the last-N window the model reads), so nothing still in
 * that window is ever pruned.
 */
export function createChatStore(
	fs: TelegramFs,
	paths: TelegramPaths,
	retentionLimit = 0,
): ChatStore {
	async function readAll(chatId: string): Promise<ChatMessageRecord[]> {
		const path = paths.chatFile(chatId);
		if (!(await fs.exists(path))) {
			return [];
		}
		const text = await fs.readText(path);
		const records: ChatMessageRecord[] = [];
		for (const line of text.split("\n")) {
			if (!line.trim()) continue;
			try {
				records.push(JSON.parse(line) as ChatMessageRecord);
			} catch {
				// Tolerate a partial/corrupt trailing line from an interrupted append.
			}
		}
		return records;
	}

	return {
		async append(chatId, record) {
			const path = paths.chatFile(chatId);
			const line = `${JSON.stringify(record)}\n`;
			if (retentionLimit <= 0) {
				await fs.appendText(path, line);
				return;
			}
			// Append then lazily compact under a lock (so a concurrent append can't be
			// dropped by the rewrite). Only rewrite once the log passed twice the
			// retention window, trimming back to the last `retentionLimit`; this
			// amortises the rewrite to ~once per `retentionLimit` appends and always
			// keeps at least the full window on disk.
			await withFileWriteLock(path, async () => {
				await fs.appendText(path, line);
				const all = await readAll(chatId);
				if (all.length > retentionLimit * 2) {
					const kept = all.slice(-retentionLimit);
					await fs.writeTextAtomic(
						path,
						`${kept.map((r) => JSON.stringify(r)).join("\n")}\n`,
					);
				}
			});
		},
		async getRecent(chatId, limit) {
			const all = await readAll(chatId);
			return limit >= 0 ? all.slice(-limit) : all;
		},
		all: readAll,
		async hasHistory(chatId) {
			const path = paths.chatFile(chatId);
			if (!(await fs.exists(path))) return false;
			return (await fs.readText(path)).trim().length > 0;
		},
		async listChatIds() {
			const entries = await safeReaddir(fs, paths.chatsDir);
			return entries
				.filter((name) => name.endsWith(".jsonl"))
				.map((name) => name.slice(0, -".jsonl".length));
		},
	};
}
